// src/data/packages/exclusivePackages.js

const exclusivePackages = [
  {
    id: 1,
    title: "🚀 Cosmic Crossover",
    description: <>🔓 Unlock <strong>50 Gems</strong></>,
    price: "500 ⭐",
    tonAmount: "14.350",
    gems: 50,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 2,
    title: "💫 Infinity Saga",
    description: <>🔓 Unlock <strong>100 Gems</strong></>,
    price: "1,000 ⭐",
    tonAmount: "2.870",
    gems: 100,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 3,
    title: "🌌 Omniverse Mastery",
    description: <>🔓 Unlock <strong>150 Gems</strong></>,
    price: "1,500 ⭐",
    tonAmount: "4.305",
    gems: 150,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 4,
    title: "🔮 Secret Saga",
    description: <>🔓 Unlock <strong>300 Gems</strong></>,
    price: "3,000 ⭐",
    tonAmount: "8.610",
    gems: 300,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 5,
    title: "⚡ Infinity Warfront",
    description: <>🔓 Unlock <strong>500 Gems</strong></>,
    price: "5,000 ⭐",
    tonAmount: "14.350",
    gems: 500,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 6,
    title: "🌀 Quantum Rebirth",
    description: <>🔓 Unlock <strong>1K Gems</strong></>,
    price: "10,000 ⭐",
    tonAmount: "28.700",
    gems: 1000,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 7,
    title: "❄ Absolute Zero Hour",
    description: <>🔓 Unlock <strong>2K Gems</strong></>,
    price: "20,000 ⭐",
    tonAmount: "57.400",
    gems: 2000,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 8,
    title: "🛑 The Endgame",
    description: <>🔓 Unlock <strong>5K Gems</strong></>,
    price: "50,000 ⭐",
    tonAmount: "143.500",
    gems: 5000,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
  {
    id: 9,
    title: "👑 Tonmics Legend",
    description: <>🔓 Unlock <strong>10K Gems</strong></>,
    price: "100,000 ⭐",
    tonAmount: "287.000",
    gems: 10000,
    keys: 0,
    tmsPoints: 0,
    wide: false,
  },
];

export default exclusivePackages;
